---
label: Doc
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: lead
  label: lead
- type: datetime
  name: date
  label: date
- type: datetime
  name: lastmod
  label: lastmod
- type: list
  name: images
  label: images
